### ISSUE TITLE
Any plans to have Rust version of NVtrust?

### ISSUE THREAD

**Issue by Xynnn007** [NVIDIA/nvtrust#86]
Hi folks! I am new here and now working on [CNCF Confidential Containers Project](https://github.com/confidential-containers) which would provide an universal attestation framework to apply for different kinds of TEEs. Currently we have `Intel TDX/SGX`, `AMD SNP`, `Arm CCA`, `Azure vTPM platforms` etc., and we want to integrate Nvidia GPU pretty much as well. Given that Rust is a language that emphasizes memory safety and is very suitable for confidential computing, all our stacks are built on top of Rust. Do you folks have any plan to Rust-ify NVtrust suites now? Thanks!

**Comment by steven-bellock** [comment]
When you say "universal attestation framework" do you mean it can be used in non-(Confidental Container) environments? Or does universal means it supports all TEEs, such as TDX/SNP/CCA, etc?

In terms of languages, that is partly influenced by the language of the attestation framework(s). Currently, the nvTrust attestation SDK is written in Python, which is supposedly memory-safe. In addition end users do not perform verification of attestation results all that often, so presumably they don't need the performance of Rust over Python. When you ask about Rust support, is that so that an NVIDIA attestation solution can be easily integrated into the current framework? Or is it difficult/impossible for a Python-based SDK to be integrated?

For the container aspect @zvonkok seems to be most knowledgeable. He might have more information on what is publicly shareable.

**Comment by Xynnn007** [comment]
@steven-bellock  Thanks for the comments!
Hey @zvonkok nice to see you here.

> When you say "universal attestation framework" do you mean it can be used in non-(Confidental Container) environments? Or does universal means it supports all TEEs, such as TDX/SNP/CCA, etc?

Sorry for the wrong word. I mean "it supports all TEEs".


> is that so that an NVIDIA attestation solution can be easily integrated into the current framework? Or is it difficult/impossible for a Python-based SDK to be integrated?

We now can use rust command to fork a python child process to execute the python-based sdk, but this requires the execution environment have python suites and supporting whls installed. For CoCo this is not perfect and will have strong requirement for the environment. If we have solutions of an SDK for non-scripting languages that can be compiled into executable files/libraries, e.g. Rust, it would do great help.

**Comment by steven-bellock** [comment]
>this requires the execution environment have python suites and supporting whls installed.

For ML frameworks like PyTorch and TensorFlow, Python will already need to be present in the container. But yes, it seems like it would be good to have a compilable codebase with optional scripting language wrappers.

**Comment by thisiskarthikj** [comment]
@Xynnn007 We are currently evaluating customer preferences, security, usability, and other factors for the next iteration of the Attestation SDK. We will keep you informed about the next steps

**Comment by fitzthum** [comment]
+1 a Rust version of these components would be extremely valuable imo

**Comment by jorgeantonio21** [comment]
+1 on this
